In [260]:
import pandas

movie_db = pandas.read_csv('./moviedb.csv')
movie_db = movie_db.fillna('')
movie_db['duration'] = movie_db['duration'].str.replace(',', '')
movie_db['duration'] = movie_db['duration'].str.replace(' ', '')
movie_db['duration'] = movie_db['duration'].str.replace('m', '')
movie_db['duration'] = movie_db['duration'].str.replace('h', ':')

movie_db

,title,original_title,date,public,duration,genre,synopsis,note,actors,original_language,original_country
0,Les Évadés,Original title: The Shawshank Redemption,"March 1, 1995 (France)",Tous publics,2:22,Drama,Two imprisoned men bond over a number of years...,9.3,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",English,United States
1,Entre le ciel et l'enfer,Original title: Tengoku to jigoku,"June 9, 1976 (France)",Tous publics,2:23,"Crime,Drama,Mystery",An executive of a Yokohama shoe company become...,8.4,"Toshirô Mifune,Yutaka Sada,Tatsuya Nakadai,Kyô...",Japanese,Japan
2,Le Bateau,Original title: Das Boot,"February 17, 1982 (France)",Tous publics,2:29,"Adventure,Drama,Thriller",The claustrophobic world of a WWII German U-bo...,8.3,"Jürgen Prochnow,Herbert Grönemeyer,Klaus Wenne...",German,West Germany
3,Avengers: Endgame,,"April 24, 2019 (France)",Tous publics,3:1,"Action,Adventure,Drama",After the devastating events of Avengers: Infi...,8.4,"Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chr...","English,Japanese,Xhosa,German",United States
4,Aliens : Le Retour,Original title: Aliens,"October 8, 1986 (France)",13,2:17,"Action,Adventure,Sci-Fi",Fifty-seven years after surviving an apocalypt...,8.3,"Sigourney Weaver,Michael Biehn,Carrie Henn,Pau...",English,"United Kingdom,United States"
...,...,...,...,...,...,...,...,...,...,...,...
245,La liste de Schindler,Original title: Schindler's List,"March 2, 1994 (France)",Tous publics,3:15,"Biography,Drama,History","In German-occupied Poland during World War II,...",8.9,"Liam Neeson,Ralph Fiennes,Ben Kingsley,Carolin...","English,Hebrew,German,Polish,Latin",United States
246,12 Hommes en colère,Original title: 12 Angry Men,"September 4, 1957 (France)",Tous publics,1:36,"Crime,Drama",The jury in a New York City murder trial is fr...,9.0,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",English,United States
247,"Le Parrain, 2ᵉ partie",Original title: The Godfather: Part II,"August 27, 1975 (France)",13,3:22,"Crime,Drama",The early life and career of Vito Corleone in ...,9.0,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...","English,Italian,Spanish,Latin,Sicilian",United States
248,The Dark Knight : Le Chevalier noir,Original title: The Dark Knight,"August 13, 2008 (France)",Tous publics,2:32,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,9.0,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...","English,Mandarin","United States,United Kingdom"
249,Le Parrain,Original title: The Godfather,"October 18, 1972 (France)",12,2:55,"Crime,Drama",The Godfather follows Vito Corleone Don of the...,9.2,"Marlon Brando,Al Pacino,James Caan,Diane Keato...","English,Italian,Latin",United States

In [285]:
movie_db['years'] = movie_db['date'].str.extract(r', (\d+)')
movie_db

,title,original_title,date,public,duration,genre,synopsis,note,actors,original_language,original_country,years
0,Les Évadés,Original title: The Shawshank Redemption,"March 1, 1995 (France)",Tous publics,2:22,Drama,Two imprisoned men bond over a number of years...,9.3,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",English,United States,1995
1,Entre le ciel et l'enfer,Original title: Tengoku to jigoku,"June 9, 1976 (France)",Tous publics,2:23,"Crime,Drama,Mystery",An executive of a Yokohama shoe company become...,8.4,"Toshirô Mifune,Yutaka Sada,Tatsuya Nakadai,Kyô...",Japanese,Japan,1976
2,Le Bateau,Original title: Das Boot,"February 17, 1982 (France)",Tous publics,2:29,"Adventure,Drama,Thriller",The claustrophobic world of a WWII German U-bo...,8.3,"Jürgen Prochnow,Herbert Grönemeyer,Klaus Wenne...",German,West Germany,1982
3,Avengers: Endgame,,"April 24, 2019 (France)",Tous publics,3:1,"Action,Adventure,Drama",After the devastating events of Avengers: Infi...,8.4,"Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chr...","English,Japanese,Xhosa,German",United States,2019
4,Aliens : Le Retour,Original title: Aliens,"October 8, 1986 (France)",13,2:17,"Action,Adventure,Sci-Fi",Fifty-seven years after surviving an apocalypt...,8.3,"Sigourney Weaver,Michael Biehn,Carrie Henn,Pau...",English,"United Kingdom,United States",1986
...,...,...,...,...,...,...,...,...,...,...,...,...
245,La liste de Schindler,Original title: Schindler's List,"March 2, 1994 (France)",Tous publics,3:15,"Biography,Drama,History","In German-occupied Poland during World War II,...",8.9,"Liam Neeson,Ralph Fiennes,Ben Kingsley,Carolin...","English,Hebrew,German,Polish,Latin",United States,1994
246,12 Hommes en colère,Original title: 12 Angry Men,"September 4, 1957 (France)",Tous publics,1:36,"Crime,Drama",The jury in a New York City murder trial is fr...,9.0,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",English,United States,1957
247,"Le Parrain, 2ᵉ partie",Original title: The Godfather: Part II,"August 27, 1975 (France)",13,3:22,"Crime,Drama",The early life and career of Vito Corleone in ...,9.0,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...","English,Italian,Spanish,Latin,Sicilian",United States,1975
248,The Dark Knight : Le Chevalier noir,Original title: The Dark Knight,"August 13, 2008 (France)",Tous publics,2:32,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,9.0,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...","English,Mandarin","United States,United Kingdom",2008
249,Le Parrain,Original title: The Godfather,"October 18, 1972 (France)",12,2:55,"Crime,Drama",The Godfather follows Vito Corleone Don of the...,9.2,"Marlon Brando,Al Pacino,James Caan,Diane Keato...","English,Italian,Latin",United States,1972

In [300]:
#Changing the duration to only minutes

# movie_db['hours'] = movie_db['duration'].str.extract(r'(\d+):')
# movie_db['hours'] = movie_db['hours'].astype(float, errors = 'raise')
# movie_db['minutes'] = movie_db['duration'].str.extract(r'\d+:(\d+)')
# movie_db['minutes'] = movie_db['minutes'].astype(float, errors = 'raise')
# movie_db['full_m_duration'] = movie_db['hours'] * 60 + movie_db['minutes']
# movie_db['full_m_duration']
movie_db

,title,original_title,date,public,duration,genre,synopsis,note,actors,original_language,original_country,years,hours,minutes
0,Les Évadés,Original title: The Shawshank Redemption,"March 1, 1995 (France)",Tous publics,142.0,Drama,Two imprisoned men bond over a number of years...,9.3,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",English,United States,1995,2.0,22.0
1,Entre le ciel et l'enfer,Original title: Tengoku to jigoku,"June 9, 1976 (France)",Tous publics,143.0,"Crime,Drama,Mystery",An executive of a Yokohama shoe company become...,8.4,"Toshirô Mifune,Yutaka Sada,Tatsuya Nakadai,Kyô...",Japanese,Japan,1976,2.0,23.0
2,Le Bateau,Original title: Das Boot,"February 17, 1982 (France)",Tous publics,149.0,"Adventure,Drama,Thriller",The claustrophobic world of a WWII German U-bo...,8.3,"Jürgen Prochnow,Herbert Grönemeyer,Klaus Wenne...",German,West Germany,1982,2.0,29.0
3,Avengers: Endgame,,"April 24, 2019 (France)",Tous publics,181.0,"Action,Adventure,Drama",After the devastating events of Avengers: Infi...,8.4,"Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chr...","English,Japanese,Xhosa,German",United States,2019,3.0,1.0
4,Aliens : Le Retour,Original title: Aliens,"October 8, 1986 (France)",13,137.0,"Action,Adventure,Sci-Fi",Fifty-seven years after surviving an apocalypt...,8.3,"Sigourney Weaver,Michael Biehn,Carrie Henn,Pau...",English,"United Kingdom,United States",1986,2.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,La liste de Schindler,Original title: Schindler's List,"March 2, 1994 (France)",Tous publics,195.0,"Biography,Drama,History","In German-occupied Poland during World War II,...",8.9,"Liam Neeson,Ralph Fiennes,Ben Kingsley,Carolin...","English,Hebrew,German,Polish,Latin",United States,1994,3.0,15.0
246,12 Hommes en colère,Original title: 12 Angry Men,"September 4, 1957 (France)",Tous publics,96.0,"Crime,Drama",The jury in a New York City murder trial is fr...,9.0,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",English,United States,1957,1.0,36.0
247,"Le Parrain, 2ᵉ partie",Original title: The Godfather: Part II,"August 27, 1975 (France)",13,202.0,"Crime,Drama",The early life and career of Vito Corleone in ...,9.0,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...","English,Italian,Spanish,Latin,Sicilian",United States,1975,3.0,22.0
248,The Dark Knight : Le Chevalier noir,Original title: The Dark Knight,"August 13, 2008 (France)",Tous publics,152.0,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,9.0,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...","English,Mandarin","United States,United Kingdom",2008,2.0,32.0
249,Le Parrain,Original title: The Godfather,"October 18, 1972 (France)",12,175.0,"Crime,Drama",The Godfather follows Vito Corleone Don of the...,9.2,"Marlon Brando,Al Pacino,James Caan,Diane Keato...","English,Italian,Latin",United States,1972,2.0,55.0

1) Quel est le film le plus long ?

In [301]:
column = movie_db['duration']
max_value = column.max()
print(max_value)
index = movie_db.index[movie_db['duration'] == max_value]
res = movie_db['title'][index[0]]
print(res)

321.0
Gangs of Wasseypur

2) Quels sont les 5 films les mieux notés ?

In [303]:
highest_rated = movie_db['note'].nlargest(n=5)
indexes = highest_rated.index
res_highest = movie_db.iloc[indexes]
res_highest

,title,original_title,date,public,duration,genre,synopsis,note,actors,original_language,original_country,years,hours,minutes
160,Jai Bhim,,"November 1, 2021 (France)",,164.0,"Crime,Drama",When a tribal man is arrested for a case of al...,9.5,"Suriya,Lijo Mol Jose,Manikandan,Rajisha Vijaya...",Tamil,India,2021,2.0,44.0
0,Les Évadés,Original title: The Shawshank Redemption,"March 1, 1995 (France)",Tous publics,142.0,Drama,Two imprisoned men bond over a number of years...,9.3,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",English,United States,1995,2.0,22.0
249,Le Parrain,Original title: The Godfather,"October 18, 1972 (France)",12,175.0,"Crime,Drama",The Godfather follows Vito Corleone Don of the...,9.2,"Marlon Brando,Al Pacino,James Caan,Diane Keato...","English,Italian,Latin",United States,1972,2.0,55.0
15,Soorarai Pottru,,"November 11, 2020 (France)",18,153.0,Drama,"Nedumaaran Rajangam ""Maara"" sets out to make t...",9.1,"Suriya,Paresh Rawal,Aparna Balamurali,Gaurav P...","Tamil,Hindi",India,2020,2.0,33.0
246,12 Hommes en colère,Original title: 12 Angry Men,"September 4, 1957 (France)",Tous publics,96.0,"Crime,Drama",The jury in a New York City murder trial is fr...,9.0,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",English,United States,1957,1.0,36.0

3) Dans combien de films a joué Morgan Freeman ? Tom Cruise ?

In [304]:
nb = movie_db['actors'].str.split(',', expand=True).stack().value_counts()
print(nb['Morgan Freeman'])
# nb['Tom Cruise']
# nb

7

4) Quels sont les 3 meilleurs films d’horreur ? Dramatique ? Comique ?

In [305]:
horror_indexes = movie_db.index[movie_db['genre'].str.contains('Horror')].tolist()
drama_indexes = movie_db.index[movie_db['genre'].str.contains('Drama')].tolist()
# drama_indexes = movie_db.index[movie_db['genre'].str.contains('Drama')].tolist()
a = movie_db.iloc[horror_indexes]
res_highest_horror = a['note'].nlargest(n=3)
b = res_highest_horror.index
movie_db.iloc[b]

,title,original_title,date,public,duration,genre,synopsis,note,actors,original_language,original_country,years,hours,minutes
214,Psychose,Original title: Psycho,"November 2, 1960 (France)",18,109.0,"Horror,Mystery,Thriller","A Phoenix secretary embezzles $40,000 from her...",8.5,"Anthony Perkins,Janet Leigh,Vera Miles,John Ga...",English,United States,1960,1.0,49.0
16,Shining,Original title: The Shining,"October 16, 1980 (France)",12,146.0,"Drama,Horror",A family heads to an isolated hotel for the wi...,8.4,"Jack Nicholson,Shelley Duvall,Danny Lloyd,Scat...",English,"United Kingdom,United States",1980,2.0,26.0
199,Alien - Le 8ème passager,Original title: Alien,"September 12, 1979 (France)",12,117.0,"Horror,Sci-Fi",After a space merchant vessel receives an unkn...,8.4,"Sigourney Weaver,Tom Skerritt,John Hurt,Veroni...",English,"United Kingdom,United States",1979,1.0,57.0

5) Parmi les 100 films les mieux notés, quel pourcentage sont américains ? Français ?

In [218]:
top_100_highest_rated = movie_db['note'].nlargest(n=100)
top_100_indexes = top_100_highest_rated.index
res_top_100_highest = movie_db.iloc[top_100_indexes]

best_100_us_movies = res_top_100_highest.index[res_top_100_highest['original_country'].str.contains('United States')].tolist()
best_100_fr_movies = res_top_100_highest.index[res_top_100_highest['original_country'].str.contains('France')].tolist()
print(f'Pourcentage de films Français :  {len(best_100_us_movies)} %')
print(f'Pourcentage de films Français :  {len(best_100_fr_movies)} %')

Pourcentage de films Français :  70 %
Pourcentage de films Français :  10 %

6) Quel est la durée moyenne d’un film en fonction du genre ?

In [314]:
Sci_fi_indexes = movie_db.index[movie_db['genre'].str.contains('Sci-Fi')].tolist()
Sci_fi_movies = movie_db.iloc[Sci_fi_indexes]
# Sci_fi_movies
duration_mean = Sci_fi_movies['duration'].mean()
duration_mean

134.3

In [68]:
serie_db = pandas.read_csv('./seriedb.csv')
serie_db['duration'] = serie_db['duration'].str.replace(',', '')
serie_db['duration'] = serie_db['duration'].str.replace(' ', '')
serie_db['duration'] = serie_db['duration'].str.replace('m', '')
serie_db['duration'] = serie_db['duration'].str.replace('h', ':')

serie_db

,title,type,duration,genre,synopsis,note,episode_nb,season_nb,date,actors,original_language,original_country
0,Planet Earth II,TV Mini Series,4:58,Documentary,David Attenborough returns with a new wildlife...,9.5,6,1 Season,"November 6, 2016 (United Kingdom)","David Attenborough,Elizabeth White,Michael J. ...","English,French","United Kingdom,Germany,France,China,United States"
1,Invincible,TV Series,50,"Animation,Action,Adventure",An adult animated series based on the Skybound...,8.7,13,NaN,"March 26, 2021 (France)","Steven Yeun,J.K. Simmons,Sandra Oh,Zazie Beetz...",English,United States
2,Oz,TV Series,55,"Crime,Drama,Thriller",A series chronicling the daily activities of a...,8.7,56,NaN,"December 9, 1998 (France)","Ernie Hudson,J.K. Simmons,Lee Tergesen,Dean Wi...",English,United States
3,Moi Claude empereur,TV Mini Series,11:9,"Biography,Drama,History",The history of the Roman Empire as experienced...,8.8,13,1 Season,"June 7, 1978 (France)","Derek Jacobi,John Hurt,Siân Phillips,Brian Ble...","English,German",United Kingdom
4,Dragon Ball Z,TV Series,24,"Animation,Action,Adventure","After learning that he is from another planet,...",8.7,277,NaN,"September 13, 1996 (United States)","Doc Harris,Christopher Sabat,Scott McNeil,Sean...","Japanese,English","Japan,United States,Canada"
...,...,...,...,...,...,...,...,...,...,...,...,...
245,Sur écoute,TV Series,59,"Crime,Drama,Thriller","The Baltimore drug scene, as seen through the ...",9.3,60,NaN,"January 8, 2004 (France)","Dominic West,Lance Reddick,Sonja Sohn,Wendell ...","English,Greek,Mandarin,Spanish",United States
246,Chernobyl,TV Mini Series,5:30,"Drama,History,Thriller","In April 1986, an explosion at the Chernobyl n...",9.4,5,1 Season,"May 7, 2019 (France)","Jessie Buckley,Jared Harris,Stellan Skarsgård,...","English,Russian,Ukrainian","United States,United Kingdom"
247,Frères d'armes,TV Mini Series,9:54,"Action,Drama,History",The story of Easy Company of the U.S. Army 101...,9.4,10,1 Season,"July 22, 2002 (France)","Scott Grimes,Damian Lewis,Ron Livingston,Shane...","English,Dutch,French,German,Lithuanian","United States,United Kingdom"
248,Breaking Bad,TV Series,49,"Crime,Drama,Thriller",A high school chemistry teacher diagnosed with...,9.4,62,NaN,"October 9, 2010 (France)","Bryan Cranston,Aaron Paul,Anna Gunn,Betsy Bran...","English,Spanish",United States
249,Planète Terre,TV Mini Series,8:58,Documentary,"Emmy Award-winning, 11 episodes, five years in...",9.4,11,1 Season,"February 27, 2006 (United Kingdom)","David Attenborough,Sigourney Weaver,Nikolay Dr...",English,United Kingdom